### ISSUE TITLE
nice is not applied, railsbench fails to bundle install

### ISSUE THREAD

**Issue by eregon** [Shopify/yjit-bench#3]
Hello,

I've been trying to run this and noticed that the generated command:
```
setarch x86_64 -R nice -20 taskset -c 11 ruby --yjit -I ./harness benchmarks/optcarrot/benchmark.rb
```
actually causes the process to have a nice level of 19, the least priority, when trying locally on Linux.

It seems one needs `nice -n -40` (can be tested with `nice -n -40 sleep 1000`) to actually use a negative nice level, and that also needs `sudo` (otherwise: `nice: cannot set niceness: Permission denied` and it has no effect).

BTW, I also noticed `run_benchmarks.rb` uses 4 spaces as indentation which is quite unusual for Ruby. I'd make a PR for it, but it's probably best if you change it to avoid any conflict.

Finally, my run failed with:
```
$ ./run_benchmarks.rb
...
Running benchmark "railsbench" (12/13)
setarch x86_64 -R nice -20 taskset -c 11 ruby --yjit -I ./harness benchmarks/railsbench/benchmark.rb
Could not find concurrent-ruby-1.1.8 in any of the sources
Run `bundle install` to install missing gems.
./run_benchmarks.rb:13:in `check_call': RuntimeError (RuntimeError)
	from ./run_benchmarks.rb:220:in `block in run_benchmarks'
	from ./run_benchmarks.rb:188:in `each'
	from ./run_benchmarks.rb:188:in `each_with_index'
	from ./run_benchmarks.rb:188:in `run_benchmarks'
	from ./run_benchmarks.rb:282:in `<main>'
zsh: exit 1     ./run_benchmarks.rb
```

So I guess one should `bundle install` before in `benchmarks/railsbench` (either in README or by the harness).
`bundle install` currently fails though due to mimemagic 0.3.5 being yanked.

**Comment by maximecb** [comment]
Thanks @eregon

I'll investigate the `nice` question on Monday.

> I also noticed run_benchmarks.rb uses 4 spaces as indentation which is quite unusual for Ruby

The usual way Ruby code uses 2 spaces just makes code harder to read IMO. It makes it harder to tell what's indented with what, and when you're working with C or Java code with 4 space indentations all day, the context switch doesn't help the matter.

Since you are here, I'm assuming you may be wanting to compare the performance of YJIT against that of TruffleRuby. Hence, I'm going to restate what I said in my presentation earlier this week: we are very early in the YJIT project, and we're not really ready to make any performance claims, particularly given that the design of our compiler is still evolving rapidly. From the few interactions we've had, I get the feeling that you're a very competitive person, but I would very much appreciate not seeing any public claims about the performance of YJIT in publications or blog posts until we feel like we're closer to a mature implementation and we make it more clear that we're ready to enter the competition 🙏 

Have a good weekend, and if my assumptions are wrong, feel free to call me on it 🙂

**Comment by eregon** [comment]
> Since you are here, I'm assuming [...]

Actually, I wanted to replicate the results from your talk, and take a look at how it's measured and what the synthetic benchmarks look like. I was also thinking to try running these benchmarks at some point on TruffleRuby, potentially with the same harness.
I'm well aware it's quite early days for YJIT so I have no plan to publish results, but nevertheless it seems interesting to be able to run the benchmarks.

I ended up playing around a bit with `YJIT.disasm` support and was a bit surprised `optmult` is not handled yet (I tried `i * i`), but I managed to see generated code for `optplus` with `ruby -e 'def foo(i); i + i; end; 10000.times { foo(_1) }; puts YJIT.disasm(method(:foo))'`, installing capstone and rebuilding YJIT.

BTW, is there currently a way to print compilation times of YJIT?

**Comment by maximecb** [comment]
> I ended up playing around a bit with YJIT.disasm support and was a bit surprised optmult is not handled yet

That's because we're prioritizing based on how common the operations are, and `opt_mult` isn't that common, relatively speaking, in real-world Ruby code.
