### ISSUE TITLE
Create erb template rendering benchmark

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit-bench#58]
I've been told that the erb template rendering system generated Ruby code. I'd be curious to add an erb template rendering benchmark to see how that performs. This would be good to have, particularly since erb is used by rails.

Ideally, the template(s) we use for the benchmark should have realistic complexity, ideally be based on an HTML template. We should start by checking if erb comes with performance benchmarks.

We may be able to optimize YJIT for erb, and we may also be able to get erb to alter the code it's generating to be more YJIT friendly based on our findings.

**Comment by eregon** [comment]
I *think* standard ERB was also improved in recent years.
I wonder why there is even a performance difference, there isn't that many ways to concatenate strings.
So I guess it'd be interesting to check how a given template runs on both.

**Comment by maximecb** [comment]
We should probably go for erubi (and call the benchmark `erubi`) if it's actively maintainted and the rails default 👍

**Comment by noahgibbs** [comment]
I have a beginning benchmark in this branch: https://github.com/Shopify/yjit-bench/tree/erubi_benchmark

I'm trying to figure out if I've written some sort of resource leak for it, though. Early iterations run around 600ms, and by the iteration 100 it's more like 800+ms. This is repeatable, and happens with or without YJIT active.

Right now YJIT doesn't significantly change the time taken... Which makes sense, and I'm going to need to think how we can fix it. Since Erb operates by generating Ruby source code, running it once and throwing it away, its default mode of operation is *extremely* YJIT-unfriendly. And since most uses of it (e.g. Rails templates) intentionally generate slightly-different final source depending on the values passed in, there's not a very easy workaround.

I've also tried just wrapping it in a method, but no, that's not enough to help significantly. I'll keep at it.

**Comment by maximecb** [comment]
That seems insane to me. Why would you even bother generating Ruby source if you're not going to cache it? It seems it would be faster to just interpret the template and concatenate strings?

**Comment by noahgibbs** [comment]
That version has an eval on every call, yeah. I've tried a couple of similar ones. I'll try def_method and see if that's friendlier to YJIT.

**Comment by eregon** [comment]
@maximecb I'm pretty sure Rails or Tilt caches it, but yeah this stuff really lacks good documentation.

BTW not sure about erubi vs ERB but they seem to generate extremely similar code:
```ruby
$ ruby -rerubi -e 'puts Erubi::Engine.new("hello <%= 3 * 4 %>").src'
_buf = ::String.new; _buf << 'hello '.freeze; _buf << ( 3 * 4 ).to_s;
_buf.to_s

$ ruby -rerb -e 'puts ERB.new("hello <%= 3 * 4 %>").src'
#coding:UTF-8
_erbout = +''; _erbout.<< "hello ".freeze; _erbout.<<(( 3 * 4 ).to_s); _erbout
```

**Comment by noahgibbs** [comment]
@maxime - a lot of the reason they generate Ruby source is to do things like if/else and loops the way they do, where you can loop over a chunk of text and append it repeatedly. I don't think it was chosen for speed. It would also be hard to evaluate directly, since some of what you're evaluating is loop statements, etc, and you'd have to parse arbitrarily-much of the Erb file to reach the next point you can run directly.

**Comment by eregon** [comment]
Tilt seems to clearly cache it:
https://github.com/rtomayko/tilt/blob/master/lib/tilt/erubi.rb
https://github.com/rtomayko/tilt/blob/e7432c54338f54c9e432282a83a6b6b3deb10f77/lib/tilt/template.rb#L261

I'd think live reloading templates is not hard, just recompile and redefine the method when the template file changes.
There might be some complications with how template engines handle locals though.

**Comment by eregon** [comment]
Whether YJIT is faster on the benchmark might not be a good proxy for judging whether the benchmark is right, but there should be an obvious perf difference if there is an `eval` per iteration or only one per process on CRuby.

**Comment by eregon** [comment]
> And since most uses of it (e.g. Rails templates) intentionally generate slightly-different final source depending on the values passed in, there's not a very easy workaround.

That's interesting, and indeed the source needs to be the same no matter the values of the locals for caching the code to work.
Do you have any pointer why the generated source would change?

**Comment by noahgibbs** [comment]
> And since most uses of it (e.g. Rails templates) intentionally generate slightly-different final source depending on the values passed in, there's not a very easy workaround.

> That's interesting, and indeed the source needs to be the same no matter the values of the locals for caching the code to work.
> Do you have any pointer why the generated source would change?

Hm. I had thought I'd seen cases where this was done on purpose, but I'm not finding them. I may be misremembering. I had thought I'd seen something with unrolling, but now I think I was confused :-/

I don't know for sure why Rails didn't cache the templates. But I'm pretty sure it didn't.

**Comment by maximecb** [comment]
@rafaelfranca does rails cache the generated source for ERB templates?

@noahgibbs if there's no caching, seems like an area where things could be improved. Maybe on the rails side, maybe on the ERB side. 🤔

**Comment by noahgibbs** [comment]
At this point, Rails *does* do caching. I was going back to watch the 2019 summary (https://www.youtube.com/watch?v=8Dld5kFWGCc) and it's complicated by a few things Rails does like letting you set local variables...

Which actually is what I was thinking of with the varying source, Benoit -- I was confused because Rails would routinely add a preamble to the source to set all the locals, but of course the preamble depends on how many locals, with what names, are used. Erb's output is the same, but what Rails puts into a method is not.

**Comment by noahgibbs** [comment]
I've done some local testing with code-generation time, but it sounds like that's not what we want in our benchmark suite (makes sense, that's often cached.) So instead I've filed PR #60 with the Erb template from "gem server", and a Discourse view with stubbed data, rendered in Rails -- but not Discourse, of course.
