### ISSUE TITLE
Add a Railsbench-style benchmark using latest edge Rails

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/yjit-bench#64]
We should add a benchmark that tracks latest Edge Rails. That way we'll notice if YJIT has a large performance change relative to Rails, and whether Rails has added code we do especially well or poorly on.

### Previous issue description

Railbench: update to Rails 6.1

This will require updating the Gemfile and doing a "bundle update" at a minimum. There may be other changes as well.

Rails 6.1 made some changes to template rendering that may be relevant to us (https://github.com/rails/rails/pull/43713). Thanks for pointing this out, @byroot!

**Comment by byroot** [comment]
> Rails 6.1 made some changes to template rendering that may be relevant to us (rails/rails#43713).

No that PR is Rails edge (soon to be 7).

But what I meant is that we should either test the latest rails release, or multiple releases.

And having a test for Rails edge as well would be great because it would allow us to make changes to Rails with YJIT in mind and see the results over time, but I understand how it's more maintenance work that the latest release.
